# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Vtrace' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  # Pods for Vtrace

  pod 'Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/Performance'

end
